- name: Ensure that the list of users is defined
  ansible.builtin.assert:
    that:
      - users__users is defined
      - users__users | length > 0
    fail_msg: "The variable 'users__users' must be defined and contain at least one user."

- name: Create system users
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    groups: "sudo"
    append: true
    create_home: true
    state: present
  loop: "{{ users__users }}"
  become: true

- name: Give sudo access without password to all users in 'users__users'
  ansible.builtin.template:
    src: "010_ansible-users-no-passwd"
    dest: "/etc/sudoers.d/010_ansible-users-no-passwd"
    mode: "0440"
    owner: "root"
    group: "root"
  become: true

- name: Add SSH authorized keys for users
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.authorized_keys | join('\n') }}"
    exclusive: true # Remove other keys not specified in the list
    state: present
  loop: "{{ users__users }}"
  loop_control:
    loop_var: item
    extended: true
  become: true
  when: item.authorized_keys is defined and item.authorized_keys | length > 0

- name: Set fancy shell for users
  ansible.builtin.include_role:
    name: zsh
  vars:
    zsh__user: "{{ item.name }}"
  loop: "{{ users__users }}"
  when: item.fancy_shell | default(false)
