
users__users:
  - name: "thomas"
    comment: "Thomas S"
    fancy_shell: yes
    authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILfM21iLBhwfGkk0q9UUeQCvLBtx/Mx/ImCtXvhCoFX6 Totologie@BR (no PIN)"

  - name: "emre"
    comment: "Emre U"
    fancy_shell: yes
    authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIATMhnnENiU64bmLw1MOM693w86w+8aGvC8Kg/3xtwQi Emre@1pw"

zsh__background_color: 27
