- name: Disable root user
  ansible.builtin.command: "pveum user modify root@pam --enable 0"
  become: true

- name: Create admins group
  ansible.builtin.command: "pveum group add admins"
  ignore_errors: true # Returns error if the group already exists
  become: true

- name: Give admins group admin privileges
  ansible.builtin.command: "pveum acl modify / --group admins --role Administrator"
  become: true

- name: Create Proxmox users
  ansible.builtin.command: "pveum user add {{ item.name }}@pve --groups 'admins'"
  loop: "{{ proxmox_node__users }}"
  ignore_errors: true # Returns error if the user already exists
  become: true

- name: Create LXC template for Debian (arm64)
  ansible.builtin.include_tasks:
    file: create_lxc_template.yml

- name: Advise admin to set user passwords
  ansible.builtin.debug:
    msg: "If not done already, you might want to set the passwords of Proxmox users by running: 'sudo pveum passwd [userid]@pve'"
