- name: Create folder for LXC template creation
  ansible.builtin.file:
    path: /tmp/lxc_template_creation/
    state: directory
    mode: "0755"
  become: true

- name: Copy LXC template creation script
  ansible.builtin.copy:
    src: create_lxc_template.sh
    dest: /tmp/lxc_template_creation/create_lxc_template.sh
    mode: "0755"
  become: true

- name: Copy first launch script for LXC containers
  ansible.builtin.copy:
    src: lxc_first_launch.sh
    dest: /tmp/lxc_template_creation/lxc_first_launch.sh
    mode: "0755"
  become: true

- name: Create LXC template for Debian (arm64)
  ansible.builtin.command: "/tmp/lxc_template_creation/create_lxc_template.sh"
  become: true
