- name: "Ensure variables are defined"
  ansible.builtin.assert:
    that:
      - proxmox_node__public_ipv4 is defined
      - proxmox_node__public_ipv4 != ""
      - proxmox_node__public_ipv4_subnet is defined
      - proxmox_node__public_ipv4_subnet != ""
      - proxmox_node__public_ipv4_gateway is defined
      - proxmox_node__public_ipv4_gateway != ""
      - proxmox_node__public_interface is defined
      - proxmox_node__public_interface != ""
      - proxmox_node__users is defined
      - proxmox_node__users | length > 0
    fail_msg: "One or more required variables for proxmox_node role are not defined."
  become: true

- name: Setup networking before installing Proxmox
  ansible.builtin.include_tasks:
    file: network.yml
    apply:
      tags:
        - proxmox_node_networking
  tags: proxmox_node_networking

- name: Raises an error every time
  ansible.builtin.fail:
    msg: "TODO: Remove this"

- name: Install proxmox kernel
  ansible.builtin.include_tasks:
    file: install_kernel.yml
  tags: proxmox_node_kernel

- name: Install other proxmox packages
  ansible.builtin.include_tasks:
    file: install_other_packages.yml
  tags: proxmox_node_other_packages

- name: Configure Proxmox settings
  ansible.builtin.include_tasks:
    file: config_proxmox.yml
  tags: proxmox_node_config
