- name: Set the hostname to match the inventory
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  become: true

# Refetch ansible hostname
- name: Refetch ansible hostname after change
  ansible.builtin.setup:
    gather_subset:
      - "network"
  become: true

- name: "Configure /etc/hosts with public IPv4"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ proxmox_node__public_ipv4 }}"
    line: "{{ proxmox_node__public_ipv4 }}  {{ ansible_hostname }}"
  become: true

- name: "Disable cloud-init network configuration"
  ansible.builtin.copy:
    dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
    content: |
      # Disable cloud-init network configuration
      network: {config: disabled}
    mode: "0644"
  become: true

- name: "Install ifupdown2 package"
  ansible.builtin.apt:
    name: ifupdown2
    state: present
    update_cache: true
  become: true

- name: "Delete existing /etc/network/interfaces.new file"
  ansible.builtin.file:
    path: /etc/network/interfaces.new
    state: absent
  become: true

- name: "Deploy new /etc/network/interfaces file"
  ansible.builtin.template:
    src: interfaces
    dest: /etc/network/interfaces
  become: true

- name: Advise to restart networking
  ansible.builtin.debug:
    msg: |
      The network configuration has been updated.
      A networking restart using 'sudo ifreload -a' should be performed to apply the changes.
      You could also reboot the node to ensure all changes take effect.
