- name: Install everything for proxmox containers
  hosts: proxmox_containers

  roles:
    - role: ssh_server
      tags: ssh_server
    - role: motd
      tags: motd
    - role: users
      tags: users
