- name: Install everything for Proxmox nodes
  hosts: proxmox_node

  roles:
    - role: motd
      tags: motd
    - role: users
      tags: users
    - role: ssh_server
      tags: ssh_server
    - role: proxmox_node
      tags: proxmox_node
