servers:
  children:
    proxmox_node: {}
    proxmox_containers: {}

proxmox_node:
  hosts:
    brot-thomas:
      ansible_ssh_host: brot-thomas
    brot-emre:
      ansible_ssh_host: brot-emre

# For non-Talos proxmox containers
proxmox_containers:
  hosts:
