apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: google-online-boutique
  namespace: argocd

spec:
  project: default

  destination:
    name: in-cluster
    namespace: google-online-boutique

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  source:
    repoURL: https://github.com/GoogleCloudPlatform/microservices-demo.git
    targetRevision: main
    path: helm-chart
    helm:
      releaseName: google-online-boutique
      valuesObject:
        # see: https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/helm-chart/values.yaml
        networkPolicies:
          create: true
