apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: envoy-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"

spec:
  project: default

  source:
    chart: gateway-helm
    path: gateway-helm
    repoURL: docker.io/envoyproxy
    targetRevision: v1.6.2

    # see: https://gateway.envoyproxy.io/docs/install/gateway-helm-api/
    helm:
      valuesObject:
        deployment:
          envoyGateway:
            resources:
              limits:
                cpu: 700m
                memory: 256Mi
          replicas: 2

  destination:
    namespace: envoy-gateway-system
    name: in-cluster

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
