apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool

metadata:
  name: "loadbalancer-ippool"
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

spec:
  blocks:
    # We could have more, but we just need one for Ingress
    - cidr: "192.168.1.150/32"
    - cidr: "192.168.1.151/32"
    - cidr: "2a01:e0a:a67:5151:c0:ffee::/96"

---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy

metadata:
  name: "l2-announcement-policy"
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

spec:
  loadBalancerIPs: true
  interfaces:
    - "^eth[0-9]+"
#  nodeSelector: # Could be used to use L2 announcement only on specific nodes
#    matchLabels:
#     (...)
