# Give sufficient rights to MetalLB namespace
apiVersion: v1
kind: Namespace

metadata:
  name: metallb-system
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.250-192.168.1.253

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-loadbalancer
  namespace: metallb-system
spec:
  ipAddressPools:
    - main-pool
