apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: hello-secret
  namespace: bitwarden-external-secrets

spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    # This name must match the metadata.name in the `SecretStore`
    name: bitwarden-secretsmanager
    kind: SecretStore

  data:
    - secretKey: hello
      remoteRef:
        key: "hello"
